environments {
  default {
    webdriver.base.url = "https://www.saucedemo.com"
  }

  ci {
    webdriver.base.url = "https://www.saucedemo.com"
    webdriver {
      capabilities {
        "goog:chromeOptions" {
          args = ["test-type", "no-sandbox", "ignore-certificate-errors",
                  "disable-infobars", "disable-gpu", "disable-default-apps",
                  "disable-dev-shm-usage", "window-size=1920,1080", "headless=new"]
        }
      }
    }
  }
}

webdriver {
  driver = chrome
  autodriver = true
  capabilities {
    browserName = "chrome"
    acceptInsecureCerts = true
    "goog:chromeOptions" {
      // 👇 AGREGAMOS EL ARGUMENTO AL FINAL DE ESTA LISTA:
      args = ["test-type", "no-sandbox", "ignore-certificate-errors", "start-maximized",
              "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", 
              "disable-features=PasswordLeakDetection,SafeBrowsing"]
              
      prefs {
        "credentials_enable_service" = false
        "profile.password_manager_enabled" = false
      }
    }
  }
}

serenity {
  take.screenshots = AFTER_EACH_STEP
  console.colors = true
  logging = verbose
}