[pytest]
bdd_features_base_dir = features/
python_files = *_steps.py
addopts =
    --html=reports/report.html
    --self-contained-html
    -v
    --junitxml=reports/junit.xml
    --tracing=retain-on-failure
    --alluredir=reports/allure-results
testpaths = steps
pythonpath = .
markers =
    Login: Escenarios de autenticacion
    Playwright: Escenarios ejecutados con Playwright
    Ordenamiento: Escenarios de ordenamiento de productos
